=== Jamsek-m/www.mjamsek.com/static/projects-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://www.mjamsek.com/projects.schema.json",
    "title": "mJamsek Projects",
    "description": "mJamsek project schema",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "position": {
            "type": "number",
            "description": "Order to display projects in. Lower positions are displayed sooner."
        },
        "path": {
            "type": "string",
            "description": "Path that project will be available at. Must be unique, with no lang prefixes."
        },
        "title": {
            "type": "string",
            "description": "Key for translated value of project's title."
        },
        "description": {
            "type": "string",
            "description": "Key for translated value of project's short description."
        },
        "fullDescription": {
            "type": "string",
            "description": "Key for translated value of project's full description."
        },
        "license": {
            "type": "string"
        },
        "tags": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "images": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "thumbnail": {
            "type": "string"
        },
        "distribution": {
            "type": "object",
            "$ref": "#/definitions/ProjectDistribution"
        },
        "repository": {
            "type": "object",
            "$ref": "#/definitions/ProjectRepository"
        },
        "releases": {
            "type": "array",
            "items": {
                "type": "object",
                "$ref": "#/definitions/ProjectDistribution"
            }
        }
    },
    "required": [
        "id",
        "position",
        "path",
        "title",
        "description",
        "tags",
        "fullDescription"
    ],
    "definitions": {
        "ProjectDistribution": {
            "type": "object",
            "properties": {
                "type": {
                    "$ref": "#/definitions/DistributionType"
                },
                "url": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                }
            },
            "required": [
                "type",
                "url"
            ]
        },
        "ProjectRepository": {
            "type": "object",
            "properties": {
                "provider": {
                    "$ref": "#/definitions/GitProvider"
                },
                "url": {
                    "type": "string"
                },
                "private": {
                    "type": "boolean"
                },
                "organization": {
                    "type": "string"
                }
            },
            "required": [
                "provider",
                "url"
            ]
        },
        "ProjectVersion": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string"
                },
                "releaseDate": {
                    "type": "string"
                },
                "snapshot": {
                    "type": "boolean"
                },
                "latest": {
                    "type": "boolean"
                }
            },
            "required": [
                "version"
            ]
        },
        "GitProvider": {
            "type": "string",
            "enum": [
                "github",
                "bitbucket",
                "gitlab"
            ]
        },
        "DistributionType": {
            "type": "string",
            "enum": [
                "link",
                "file"
            ]
        }
    }
}

=== Jamsek-m/www.mjamsek.com/src/content/projects/rest-client.json
{
    "id": "rest-client",
    "position": 15,
    "path": "/kumuluzee-mp-rest-client",
    "title": "projects:projects.rest-client.name",
    "description": "projects:projects.rest-client.description",
    "tags": ["Library", "REST", "KumuluzEE", "MicroProfile"],
    "fullDescription": "projects:projects.rest-client.full-description",
    "thumbnail": "/images/projects/rest-client/rest-client-1.png",
    "images": [
        "/images/projects/rest-client/rest-client-1.png",
        "/images/projects/rest-client/rest-client-2.png",
        "/images/projects/rest-client/rest-client-3.png",
        "/images/projects/rest-client/rest-client-4.jpg"
    ],
    "license": "MIT",
    "repository": {
        "provider": "github",
        "organization": "kumuluz",
        "url": "kumuluzee-rest-client"
    },
    "distribution": {
        "type": "link",
        "url": "https://mvnrepository.com/artifact/com.kumuluz.ee.rest-client/kumuluzee-rest-client"
    }
}

=== Jamsek-m/www.mjamsek.com/src/content/projects/metrics-monitor.json
{
    "id": "metrics-monitor",
    "position": 100,
    "path": "/metrics-monitor",
    "title": "projects:projects.metrics-monitor.name",
    "description": "projects:projects.metrics-monitor.description",
    "tags": ["Library","Diploma thesis"],
    "fullDescription": "projects:projects.metrics-monitor.full-description"
}

=== Jamsek-m/www.mjamsek.com/src/content/projects/kee-auth.json
{
    "id": "kee-auth",
    "position": 10,
    "path": "/kee-auth",
    "title": "projects:projects.kee-auth.name",
    "description": "projects:projects.kee-auth.description",
    "tags": [
        "Library",
        "Security",
        "KumuluzEE"
    ],
    "license": "MIT",
    "fullDescription": "projects:projects.kee-auth.full-description",
    "distribution": {
        "type": "link",
        "url": "https://mvnrepository.com/artifact/com.mjamsek.auth/kee-auth"
    },
    "repository": {
        "provider": "github",
        "url": "kee-auth"
    },
    "images": [
        "/images/projects/kee-auth/keycloak.jpg",
        "/images/projects/kee-auth/kumuluzee.png"
    ]
}

=== Jamsek-m/www.mjamsek.com/src/content/projects/prog-utils-ts.json
{
    "id": "prog-utils-ts",
    "position": 25,
    "path": "/prog-utils-ts",
    "title": "projects:projects.prog-utils-ts.name",
    "description": "projects:projects.prog-utils-ts.description",
    "fullDescription": "projects:projects.prog-utils-ts.full-description",
    "tags": [
        "Library",
        "Typescript"
    ],
    "thumbnail": "/images/projects/prog-utils-ts/typescript.png",
    "images": [
        "/images/projects/prog-utils-ts/typescript.png"
    ],
    "license": "MIT",
    "repository": {
        "provider": "github",
        "url": "ts-prog-utils"
    },
    "distribution": {
        "type": "link",
        "url": "https://www.npmjs.com/package/@mjamsek/prog-utils"
    }
}

=== Jamsek-m/www.mjamsek.com/src/content/projects/ngx-config.json
{
    "id": "ngx-config",
    "position": 20,
    "path": "/ngx-config",
    "title": "projects:projects.ngx-config.name",
    "description": "projects:projects.ngx-config.description",
    "fullDescription": "projects:projects.ngx-config.full-description",
    "tags": [
        "Library",
        "Angular",
        "Config"
    ],
    "license": "MIT",
    "distribution": {
        "type": "link",
        "url": "https://www.npmjs.com/package/@mjamsek/ngx-config"
    },
    "thumbnail": "/images/projects/ngx-config/angular.png",
    "images": [
        "/images/projects/ngx-config/angular.png"
    ],
    "repository": {
        "provider": "github",
        "url": "ngx-config"
    }
}
